### PR TITLE
Allow library to be used in parallel

### PR DESCRIPTION
**Pull request by dadgar**
This PR allows concurrent calls to Parse. Further it makes the test be
part of the same package.

Fixes https://github.com/gorhill/cronexpr/issues/26

### CODE REVIEW

**Comment by dadgar** [comment]
@gorhill Is there any reason you aren't merging this?

**Comment by gorhill** [comment]
I haven't touched the code here for years, and anything than trivial changes would require me to devote a lot of time to code review since I would need to all get back how the code works to ensure no regression.

**Comment by dadgar** [comment]
Well if it is of any use to you in your decision, HashiCorp Nomad has been shipping with a fork with this change for many months on tens of thousands of machines with no issue.

**Comment by gorhill** [comment]
> been shipping with a fork with this change for many months on tens of thousands of machines with no issue

Yes, it does make a difference knowing this -- I will go ahead and merge. Thanks.

**Pull request merged**
